### ISSUE TITLE
Test against Python3

### ISSUE THREAD

**Issue by jpic** [novafloss/mock-services#17]
It's important for this testing library to be tested with Python3 in CI. Currently, tests are handled by a Makefile on CircleCI, none of which supports a test matrix of both Python 2 and 3. Options I see here is either:
- move from make to tox,
- move from circleci to travis,

What's your take on this ?

**Comment by toopy** [comment]
:+1:

**Comment by zebuline** [comment]
:up:

**Comment by FlogFr** [comment]
PR #18 merged
